# Generated by Django 5.0 on 2023-12-13 15:24

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='email@domain.com', max_length=254, null=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('opt_in', models.BooleanField(default=1, verbose_name='Receive Text Messages')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsapp.group')),
            ],
        ),
    ]
